name: pomodoro_app
description: Application Pomodoro Flutter Desktop avec Supabase

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.8.0       # Auth et requêtes Supabase
  flutter_riverpod: ^2.5.1       # (optionnel si tu l'utilises pour la logique état)
  hooks_riverpod: ^2.5.1         # (pareil si tu fais du reactive)
  intl: ^0.19.0                  # Pour formater les durées
  window_manager: ^0.3.7         # Gérer la fenêtre desktop
  flutter_local_notifications: ^16.3.2   # Notifications natives
  path_provider: ^2.1.2          # Pour certaines notifications
  flutter_hooks: ^0.20.3         # Si tu utilises des hooks
  url_launcher: ^6.2.5           # Pour liens, aide ou plus tard
  json_annotation: ^4.8.1        # Pour sérialisation éventuelle

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
